// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/campus-feed/NoticeBoardFeed.tsx": () => import("../components/mockups/campus-feed/NoticeBoardFeed.tsx"),
  "./components/mockups/campus-feed/PulseDashboardFeed.tsx": () => import("../components/mockups/campus-feed/PulseDashboardFeed.tsx"),
  "./components/mockups/campus-feed/SpacesContextFeed.tsx": () => import("../components/mockups/campus-feed/SpacesContextFeed.tsx")
};
