// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services/ServicesClassifiedGrid.tsx": () => import("../components/mockups/services/ServicesClassifiedGrid.tsx"),
  "./components/mockups/services/ServicesMarketBoard.tsx": () => import("../components/mockups/services/ServicesMarketBoard.tsx"),
  "./components/mockups/services/ServicesPriorityLane.tsx": () => import("../components/mockups/services/ServicesPriorityLane.tsx"),
  "./components/mockups/campus-feed/CampusBrief.tsx": () => import("../components/mockups/campus-feed/CampusBrief.tsx"),
  "./components/mockups/campus-feed/DarkOLED.tsx": () => import("../components/mockups/campus-feed/DarkOLED.tsx"),
  "./components/mockups/campus-feed/Editorial.tsx": () => import("../components/mockups/campus-feed/Editorial.tsx"),
  "./components/mockups/campus-feed/Mono.tsx": () => import("../components/mockups/campus-feed/Mono.tsx"),
  "./components/mockups/campus-feed/NoticeBoardFeed.tsx": () => import("../components/mockups/campus-feed/NoticeBoardFeed.tsx"),
  "./components/mockups/campus-feed/PulseDashboardFeed.tsx": () => import("../components/mockups/campus-feed/PulseDashboardFeed.tsx"),
  "./components/mockups/campus-feed/Soft.tsx": () => import("../components/mockups/campus-feed/Soft.tsx"),
  "./components/mockups/campus-feed/SpacesContextFeed.tsx": () => import("../components/mockups/campus-feed/SpacesContextFeed.tsx"),
  "./components/mockups/campus-feed/WarmI.tsx": () => import("../components/mockups/campus-feed/WarmI.tsx"),
  "./components/mockups/campus-feed/WarmII.tsx": () => import("../components/mockups/campus-feed/WarmII.tsx")
};
